# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Archive and publish artifact
        steps:
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            replaceExistingArchive: true
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
  - stage: Deploy
    displayName: Deploy
    dependsOn: Build
    jobs:
      - deployment: Deploy
        displayName: Deplot to App Service
        environment: 'static-web-app'
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: '$(AzureSubscription)'
                  appType: 'webApp'
                  appName: '$(AppServiceName)'
                  package: '$(Pipeline.Workspace)/**/*.zip'
                  deploymentMethod: 'auto'
